### ISSUE TITLE
Failed to activate the linter-jolie package

### ISSUE THREAD

**Issue by lozingaro** [fmontesi/linter-jolie#10] opened 2019-04-23 09:39 UTC
[Steps to reproduce:]

1. Restart Atom after update to version 0.10.0

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [linter-jolie](https://github.com/fmontesi/linter-jolie) package 0.10.0

### Stack Trace

Failed to activate the linter-jolie package

```
At /Users/******/.atom/packages/linter-jolie/lib/main.js: Error parsing regular expression: Invalid regular expression: /\s*(?<file>. ):\s*(?<line>\d ):\s*(?<type>error|warning)\s*:\s*(?<message>. )/: Invalid group (7:20)

SyntaxError: /Users/*****/.atom/packages/linter-jolie/lib/main.js: Error parsing regular expression: Invalid regular expression: /\s*(?<file>. ):\s*(?<line>\d ):\s*(?<type>error|warning)\s*:\s*(?<message>. )/: Invalid group (7:20)

let executablePath = atom.config.get( "linter-jolie.jolieExecutablePath" )
let messageRegex = /\s*(?<file>. ):\s*(?<line>\d ):\s*(?<type>error|warning)\s*:\s*(?<message>. )/gm

module.exports = {
	activate() {
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.tryCreateRegexp (/app.asar/node_modules/babylon/lib/tokenizer/index.js:57:42)
    at Parser.readRegexp (/app.asar/node_modules/babylon/lib/tokenizer/index.js:587:23)
    at Parser.readToken_slash (/app.asar/node_modules/babylon/lib/tokenizer/index.js:311:19)
    at Parser.getTokenFromCode (/app.asar/node_modules/babylon/lib/tokenizer/index.js:488:21)
    at Parser.readToken (/app.asar/node_modules/babylon/lib/tokenizer/index.js:160:17)
    at /app.asar/node_modules/babylon/lib/plugins/jsx/index.js:445:20)
    at Parser.readToken (/app.asar/node_modules/babylon/lib/plugins/flow.js:775:22)
    at Parser.nextToken (/app.asar/node_modules/babylon/lib/tokenizer/index.js:151:19)
    at Parser.next (/app.asar/node_modules/babylon/lib/tokenizer/index.js:88:10)
    at Parser.eat (/app.asar/node_modules/babylon/lib/tokenizer/index.js:95:12)
    at Parser.pp.parseVar (/app.asar/node_modules/babylon/lib/parser/statement.js:492:14)
    at Parser.pp.parseVarStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:370:8)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:99:19)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/app.asar/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/app.asar/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/app.asar/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/app.asar/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.e.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:577032)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:573831)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147898)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150295)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-jolie 0.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
file-icons 2.1.31 
hard-wrap 1.7.1 
intentions 1.1.5 
language-jolie 0.6.0 
language-latex 1.2.0 
latextools 0.8.5 
linter 2.3.0 
linter-jolie 0.10.0 
linter-ui-default 1.7.1 
script 3.18.1 
```

**Comment by fmontesi** [comment] 2019-04-23 15:56
Weird, I cannot reproduce this on Linux.
@thesave, what about you on MacOS? Any ideas?

**Comment by thesave** [comment] 2019-09-03 05:58
I guess we can close this and advise to switch to vscode with the [new LSP plugin for Jolie](https://marketplace.visualstudio.com/items?itemName=jolie.vscode-jolie)

**Comment by lozingaro** [comment] 2019-09-04 06:56
I suppose we could :-)

**Closed as completed** 2019-09-09 12:35 UTC
